### ISSUE TITLE
features of training data

### ISSUE THREAD

**Issue by qtz93** [Christian-lyc/SVM-for-lane-change-prediction#1]
Hello, have the training data you share been pre-processed? Can you tell me what each column of features specifically refers to? Look forward to your reply. ^_^

**Comment by Christian-lyc** [comment]
Sorry, I seldom see the comments. can you please give me your email address? I will explain it specifically

**Comment by zackfupapa** [comment]
hello，I want to chat with you by email，i have sent an email to your address，if you can my letter，i hope you can help me。Thank you！！！I am so helpless.....

**Comment by Christian-lyc** [comment]
Sorry, I didn't receive you email, 
Columns represent vertical speed, front or behind has cars(if it has, it's 1), horizontal speed, left and right cars (if it has, it's 1), trajectory and variance of horizontal speed change
